### ISSUE TITLE
iOS14 crash

### ISSUE THREAD

**Issue by THJLearn** [Abnerzj/ZJPickerView#9]

**Comment by kylesaid** [comment]
可以先注释“ZJPickerView.m”的第260到第277行，来解决iOS 14 提示的数组越界问题；
You can first comment lines 260 to 277 to solve the array overbounds problem prompted by iOS 14 in file "ZJPickerView.m"；
<img width="905" alt="截屏2020-09-24 09 42 12" src="https://user-images.githubusercontent.com/18623420/94091308-87f16280-fe4a-11ea-9c08-762176b0424c.png">

**Comment by Abnerzj** [comment]
感谢你发现的问题，调试发现，iOS14+时ZJPickerView的选中行改为框住整行，而不是上下两条分割线了。最新的版本已经发布，做了系统版本兼容处理，请更新最新版本。
Thank you for finding the problem. After debugging, it was found that the selected line of ZJPickerView was changed to frame the entire line instead of the upper and lower dividing lines in iOS14+. The latest version has been released, and the system version is compatible, please update the latest version.
